<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Call us now_logo img-responsive</name>
   <tag></tag>
   <elementGuidId>42bb65ed-d385-46b5-bb1f-e8314b0b1a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_logo']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;My Shop&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4cd75da7-a859-4a08-a101-3c03ff77dec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo img-responsive</value>
      <webElementGuid>1a746467-ddff-49f6-9304-37fb209768d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.automationpractice.pl/img/logo.jpg</value>
      <webElementGuid>4ce4379f-afb6-44b3-ad3d-12d41ab8074e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>My Shop</value>
      <webElementGuid>a07e5123-c3ad-4768-89bd-38a50ead989a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>350</value>
      <webElementGuid>b88da6e1-2562-472d-9047-36020300d704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>99</value>
      <webElementGuid>5fa551ce-ba2a-41f5-b439-194157fedccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_logo&quot;)/a[1]/img[@class=&quot;logo img-responsive&quot;]</value>
      <webElementGuid>15cd97be-82c8-4878-94a1-d2e1a3cf04c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_logo']/a/img</value>
      <webElementGuid>ee9efb06-ed82-431f-ab0b-3b7f59fd857c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='My Shop']</value>
      <webElementGuid>8f8739bd-31fb-4ad5-b1ad-bbe53e427322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/img</value>
      <webElementGuid>176e7ce5-259e-4015-a893-c7f46e45be23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://www.automationpractice.pl/img/logo.jpg' and @alt = 'My Shop']</value>
      <webElementGuid>38f5267b-15fb-4acb-9f26-bccb085b5041</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
